// Endfield Document Template
// Generated by: typst init @preview/endfield-doc:0.1.0
//
// Delete or replace any fields you don't need.
#import "@preview/endfield-doc:0.1.0": endfield-doc

#show: endfield-doc.with(
  title:       [Document Title],
  subtitle:    [Subtitle],
  author:      [Author Name],
  date:        datetime.today().display("[year]-[month]-[day]"),
  institution: [Institution],
  doc-footer:  [Institution],
  lang:        "en",
  region:      "us",
  // font-cjk:   ("HarmonyOS Sans SC",),
  // font-latin: ("HarmonyOS Sans",),
  // font-code:  ("JetBrains Mono", "Consolas"),
  // font-emoji: ("Segoe UI Emoji", "Noto Emoji"),
)

= Introduction

Your document begins here. Text flows automatically across pages.

== Background

Write your content using standard Typst markup: *bold*, _italic_,
`inline code`, and so on.

- Bullet list item
- Another item

== Goals

#lorem(40)

= Main Content

#lorem(80)

== Details

#lorem(60)
